import { Order, Member, Reward, ServicePrice } from '@/types/laundroflow';

export const SERVICE_PRICES: ServicePrice[] = [
  { type: 'Wash, Dry & Fold', pricePerKg: 45, label: 'Wash, Dry & Fold (₱45/kg)' },
  { type: 'Wash Only', pricePerKg: 30, label: 'Wash Only (₱30/kg)' },
  { type: 'Dry Clean', pricePerKg: 80, label: 'Dry Clean (₱80/kg)' },
  { type: 'Press Only', pricePerKg: 25, label: 'Press Only (₱25/kg)' },
  { type: 'Comforter', pricePerKg: 120, label: 'Comforter (₱120/kg)' },
  { type: 'Curtains', pricePerKg: 70, label: 'Curtains (₱70/kg)' },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: '1',
    ticket: '#FS-H2P8R4',
    customer: 'Roberto Aquino',
    phone: '09171234501',
    service: 'Curtains',
    weight: 4,
    amount: 280,
    status: 'Washing',
    paymentStatus: 'Unpaid',
    eta: 'Apr 6, 6:00 PM',
    date: 'Apr 4',
  },
  {
    id: '2',
    ticket: '#FS-D1F6H3',
    customer: 'Carlos Garcia',
    phone: '09171234502',
    service: 'Comforter',
    weight: 3.5,
    amount: 420,
    status: 'Washing',
    paymentStatus: 'Paid',
    eta: 'Apr 5, 10:00 PM',
    date: 'Apr 4',
  },
  {
    id: '3',
    ticket: '#FS-E4G9K7',
    customer: 'Sofia Lim',
    phone: '09211234567',
    service: 'Wash Only',
    weight: 4,
    amount: 120,
    status: 'Received',
    paymentStatus: 'Paid',
    eta: 'Apr 5, 2:00 AM',
    date: 'Apr 4',
  },
  {
    id: '4',
    ticket: '#FS-B7N4P1',
    customer: 'Juan Dela Cruz',
    phone: '09171234504',
    service: 'Dry Clean',
    weight: 2,
    amount: 160,
    status: 'Washing',
    paymentStatus: 'Unpaid',
    eta: 'Apr 5, 6:00 PM',
    date: 'Apr 4',
  },
  {
    id: '5',
    ticket: '#FS-A3K8M2',
    customer: 'Maria Santos',
    phone: '09171234567',
    service: 'Wash, Dry & Fold',
    weight: 5.2,
    amount: 234,
    status: 'Ready',
    paymentStatus: 'Paid',
    eta: 'Apr 4, 10:00 PM',
    date: 'Apr 4',
  },
  {
    id: '6',
    ticket: '#FS-G5M1N9',
    customer: 'Lisa Cruz',
    phone: '09231234567',
    service: 'Wash, Dry & Fold',
    weight: 6,
    amount: 270,
    status: 'Claimed',
    paymentStatus: 'Paid',
    eta: 'Apr 4, 6:00 PM',
    date: 'Apr 4',
  },
  {
    id: '7',
    ticket: '#FS-F8J2L6',
    customer: 'Marco Tan',
    phone: '09221234567',
    service: 'Press Only',
    weight: 2.5,
    amount: 62.5, // rounded to 63 in summary
    status: 'Ready',
    paymentStatus: 'Paid',
    eta: 'Apr 4, 8:00 PM',
    date: 'Apr 4',
  },
  {
    id: '8',
    ticket: '#FS-C9D2X5',
    customer: 'Anna Reyes',
    phone: '09191234567',
    service: 'Wash, Dry & Fold',
    weight: 8,
    amount: 360,
    status: 'Drying',
    paymentStatus: 'Paid',
    eta: 'Apr 5, 12:00 AM',
    date: 'Apr 4',
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: '1',
    name: 'Maria Santos',
    phone: '09171234567',
    email: 'maria@example.com',
    stamps: 5,
    totalStamps: 7,
    visits: 12,
    kgWashed: 63,
    rewards: 1,
  },
  {
    id: '2',
    name: 'Marco Tan',
    phone: '09221234567',
    email: 'marco@example.com',
    stamps: 6,
    totalStamps: 7,
    visits: 6,
    kgWashed: 30,
    rewards: 0,
  },
  {
    id: '3',
    name: 'Anna Reyes',
    phone: '09191234567',
    email: 'anna@example.com',
    stamps: 1,
    totalStamps: 7,
    visits: 8,
    kgWashed: 45,
    rewards: 1,
  },
  {
    id: '4',
    name: 'Sofia Lim',
    phone: '09211234567',
    email: 'sofia@example.com',
    stamps: 3,
    totalStamps: 7,
    visits: 3,
    kgWashed: 12,
    rewards: 0,
  },
  {
    id: '5',
    name: 'Lisa Cruz',
    phone: '09231234567',
    email: 'lisa@example.com',
    stamps: 1,
    totalStamps: 7,
    visits: 15,
    kgWashed: 85,
    rewards: 2,
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: '1',
    title: 'Free Wash',
    description: '1 free wash (up to 5kg)',
    member: 'Unknown',
    isRedeemed: false,
  },
  {
    id: '2',
    title: '50% Off',
    description: '50% off next order',
    member: 'Unknown',
    isRedeemed: false,
  },
];
